@if (get_row_layout() == 'explorer')
<!-- Bootstrap Icons -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
<!-- Maphilight -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/maphilight/1.4.0/jquery.maphilight.min.js"></script>
<!-- ImageMapResizer -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/image-map-resizer/1.0.10/js/imageMapResizer.js"></script> -->

<style>
    .content-div {
        display: none; /* Hidden by default */
        background-color: #212721;
        padding: 20px;
        color: #fff;
    }

    .content-div img {
        width: 100%;
        height: 100%;
        object-fit: contain;
        max-width: 100%;
        max-height: 100vh;
    }
</style>

<section class="block bg-casa-light pt-5" id="explorer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 p-0">
                @if (get_sub_field('header'))
                    <h2 class="pt-5 pb-3 text-center font-black">
                        @php the_sub_field('header') @endphp
                    </h2>
                @endif
                @if (get_sub_field('sub_header'))
                    <p class="pb-5 text-center">
                        @php the_sub_field('sub_header') @endphp
                    </p>
                @endif
                <div class="map-container">
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img src="@asset('images/explorer/explorer_main.jpg')" usemap="#image-map" class="map">

                    <map name="image-map">
                        <area target="_self" alt="Left Side" title="Left Side" href="#leftModalWindow"
                            coords="2,778,30,829,89,889,157,945,194,970,266,983,332,983,399,899,447,865,493,856,541,832,601,808,642,782,684,767,800,725,830,719,824,639,784,512,765,463,736,453,663,461,520,550,442,604,347,650" 
                            shape="poly"
                            data-title="Left Side"
                            data-content="This is the left side."
                            data-image="path/to/your-details-image.jpg"
                            data-url="left.html"
                            data-fade-in-image="@asset('images/explorer/explorer_left_side.jpg')">
                        <area target="_self" alt="Center" title="Center" href="center" coords="787,448,820,550,828,607,838,677,840,717,884,749,989,776,1042,781,1078,798,1110,814,1177,817,1212,817,1382,611,1488,501,1511,436,1496,409,1463,406" shape="poly">
                        <area target="_self" alt="Right Side" title="Right Side" href="right" coords="1236,814,1275,830,1305,838,1399,854,1458,859,1542,864,1620,876,1697,825,1775,765,1779,744,1609,639,1463,566,1420,598,1379,641,1352,670,1313,720,1288,749,1267,781" shape="poly">
                    </map>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Content Div -->
<div id="contentDiv" class="content-div">
    <button type="button" class="btn-close" id="closeContentDiv" aria-label="Close"></button>
    <div class="content-body">
        @if (shortcode_exists('drawattention'))
            {!! do_shortcode('[drawattention]') !!}
        @endif
    </div>
</div>

<script>
    jQuery(document).ready(function($){
        // Initialize the Maphilight plugin
        $('img').maphilight({
            fillColor: '008800',
            strokeColor: '008800',
        });

        // Initialize ImageMapResizer plugin
        // $('map').imageMapResize();

        // Show the content div when the area with href="#leftModalWindow" is clicked
        $('area[href="#leftModalWindow"]').click(function(event) {
            event.preventDefault(); // Prevent default link behavior
            $('#contentDiv').show();
        });

        // Close the content div
        $('#closeContentDiv').click(function() {
            $('#contentDiv').hide();
        });
    });
</script>

@endif
